using Baskets.WebApi;
using Baskets.WebApi.Features;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);
builder.AddExceptionMapper(builder =>
{
    builder
        .Map<DbUpdateException>()
        .ToStatusCode(StatusCodes.Status409Conflict)
    ;
    builder
        .Map<DbUpdateConcurrencyException>()
        .ToStatusCode(StatusCodes.Status409Conflict)
    ;
});
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(o => o.CustomSchemaIds(type => type.FullName?.Replace("+", ".")));
builder.AddFeatures();

var app = builder.Build();
app.UseExceptionMapper();
app.MapFeatures();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseDarkSwaggerUi();
}

app.Run();

// Workaround that makes the autogenerated program public so tests can
// access it without granting internal visibility.
#pragma warning disable CA1050 // Declare types in namespaces
public partial class Program
{
}
